// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFA9lb4gtFf_kk-af9Ueg3gjSu5qEYJ7w',
    appId: '1:711580164358:web:38a363b3f39fd8e1e03e87',
    messagingSenderId: '711580164358',
    projectId: 'yalla-talk-app-95f4d',
    authDomain: 'yalla-talk-app-95f4d.firebaseapp.com',
    storageBucket: 'yalla-talk-app-95f4d.firebasestorage.app',
    measurementId: 'G-V226B0KPBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpxN2pRzzQThKHIAJUUdLvPLFiBKM-33g',
    appId: '1:711580164358:android:c380d0fc4696d743e03e87',
    messagingSenderId: '711580164358',
    projectId: 'yalla-talk-app-95f4d',
    storageBucket: 'yalla-talk-app-95f4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7sx8M7vVT-xD6y5y_rqUaBVrnk_stKE0',
    appId: '1:711580164358:ios:1290a3614cbd0cdde03e87',
    messagingSenderId: '711580164358',
    projectId: 'yalla-talk-app-95f4d',
    storageBucket: 'yalla-talk-app-95f4d.firebasestorage.app',
    iosBundleId: 'com.example.yallaTalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7sx8M7vVT-xD6y5y_rqUaBVrnk_stKE0',
    appId: '1:711580164358:ios:1290a3614cbd0cdde03e87',
    messagingSenderId: '711580164358',
    projectId: 'yalla-talk-app-95f4d',
    storageBucket: 'yalla-talk-app-95f4d.firebasestorage.app',
    iosBundleId: 'com.example.yallaTalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFA9lb4gtFf_kk-af9Ueg3gjSu5qEYJ7w',
    appId: '1:711580164358:web:01636576786b0e51e03e87',
    messagingSenderId: '711580164358',
    projectId: 'yalla-talk-app-95f4d',
    authDomain: 'yalla-talk-app-95f4d.firebaseapp.com',
    storageBucket: 'yalla-talk-app-95f4d.firebasestorage.app',
    measurementId: 'G-ZN7PL1CCSZ',
  );
}
