// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7OjHZuacMQL5DmeqxDQDM_T-3PY_PFWk',
    appId: '1:872514974182:web:4532babeda6827811ce627',
    messagingSenderId: '872514974182',
    projectId: 'yalla-talk-99138',
    authDomain: 'yalla-talk-99138.firebaseapp.com',
    storageBucket: 'yalla-talk-99138.firebasestorage.app',
    measurementId: 'G-R2RMS7HQG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gmNTLKCMfrSC0gVZLIke3PVanz76dks',
    appId: '1:872514974182:android:55cf33749a0ef3e61ce627',
    messagingSenderId: '872514974182',
    projectId: 'yalla-talk-99138',
    storageBucket: 'yalla-talk-99138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgQRKY8tFyLp22Z7dm_yceHwOJyh9X38',
    appId: '1:872514974182:ios:1a9a41a2274d743c1ce627',
    messagingSenderId: '872514974182',
    projectId: 'yalla-talk-99138',
    storageBucket: 'yalla-talk-99138.firebasestorage.app',
    iosBundleId: 'com.example.yallaTalkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsgQRKY8tFyLp22Z7dm_yceHwOJyh9X38',
    appId: '1:872514974182:ios:1a9a41a2274d743c1ce627',
    messagingSenderId: '872514974182',
    projectId: 'yalla-talk-99138',
    storageBucket: 'yalla-talk-99138.firebasestorage.app',
    iosBundleId: 'com.example.yallaTalkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7OjHZuacMQL5DmeqxDQDM_T-3PY_PFWk',
    appId: '1:872514974182:web:ed16cadf02a6b6de1ce627',
    messagingSenderId: '872514974182',
    projectId: 'yalla-talk-99138',
    authDomain: 'yalla-talk-99138.firebaseapp.com',
    storageBucket: 'yalla-talk-99138.firebasestorage.app',
    measurementId: 'G-SJ4LKQNBV9',
  );

}